- Cargo.lock
- Cargo.toml
- device/Cargo.toml
- device/src/esp32_run.rs
- device/src/io.rs
- frostsnap_comms/src/lib.rs
- frostsnap_coordinator/src/serial_port.rs
- frostsnap_core/src/encrypted_share.rs
- frostsnap_core/src/lib.rs
- frostsnap_core/src/message.rs
Fixes allocation failures https://github.com/frostsnap/frostsnap/issues/58 , I haven't got any after signing many times (5+, 4-of-4) in a row with similar timed presses.
Things feel much faster in general.
Marking draft because
- ~[ ] `upstream_buffer_uart` and `upstream_buffer_jtag` could be from the same buffer.~
> Serial Ring Buffer

- coordinator-cli/src/main.rs
- coordinator-cli/src/signer.rs
- frostsnap_coordinator/src/signing.rs
- frostsnap_core/src/coordinator.rs
- frostsnap_core/src/device.rs
- frostsnap_core/src/encrypted_share.rs
- frostsnap_core/src/lib.rs
- frostsnap_core/src/message.rs
- frostsnap_core/tests/common/mod.rs
- frostsnap_core/tests/endtoend.rs
- frostsnap_core/tests/malicious.rs
- frostsnapp/native/src/coordinator.rs
Currently we use a hash of the DeviceId to determine the scalar party index.
But we want to use small simple indices (`1,2,3,...`) to achieve significantly smaller backups (1 bech32m character vs 52 characters).
This PR is WIP exploration of having the coordinators decide these party indexes during keygen.
Signers will need to remember their share index (inside `FrostsnapKey`).
Coordinators will want to remember `BTreeMap<DeviceId, ShareIndex>`
> Small share indicies

- Cargo.lock
- Cargo.toml
- device/Cargo.toml
- device/src/bin/frostypede.rs
- device/src/esp32_run.rs
- frostsnap_core/Cargo.toml
- frostsnap_core/src/device.rs
- frostsnap_core/tests/common/mod.rs
- frostsnap_core/tests/endtoend.rs
- frostsnap_core/tests/malicious.rs
A `Hal::Rng` `seed_rng` seeds a `ChaCha20Rng` which is passed into `recv_coordinator_message()`.
We also use this rng to seed the `aux_rand`, stored and used for nonce generation (note: we discussed we might later change this seed to some pubkey/HMAC from coordinator).
> [core] non-deterministic keygen

- .github/workflows/test.yml
- Cargo.lock
- device/.cargo/config.toml
- device/Cargo.toml
- device/rust-toolchain.toml
- device/src/bin/frostypede.rs
- device/src/esp32_run.rs
- device/src/io.rs
- device/src/st7735.rs
- frostsnapp/lib/bridge_definitions.freezed.dart
- frostsnapp/native/src/api.rs
This allows us to drop the nightly toolchain. I deleted the toolchain.toml file.
One peculiar thing I had to do was lower the heap size to avoid some allocation failures. It would be really good to understand why this was necessary before merging.
Main benefit of this is that it seems to fix the problem of panic messages not being displayed in the panic handler. Note i'm not sure if that's to do with lowering the heap size or just the dependency upgrade.
This is on top of #117
> Upgrade esp-hal v0.16.1

- Cargo.lock
- Cargo.toml
- frostsnap_core/Cargo.toml
- frostsnap_core/src/coordinator.rs
- frostsnap_core/src/device.rs
- frostsnap_core/src/lib.rs
- frostsnap_core/src/message.rs
- frostsnap_core/src/tweak.rs
- frostsnap_core/src/xpub.rs
- frostsnap_core/tests/endtoend.rs
- frostsnapp/ios/Runner/bridge_generated.h
- frostsnapp/lib/bridge_definitions.dart
- frostsnapp/lib/bridge_generated.dart
- frostsnapp/lib/bridge_generated.io.dart
- frostsnapp/lib/bridge_generated.web.dart
- frostsnapp/lib/wallet.dart
- frostsnapp/macos/Runner/bridge_generated.h
- frostsnapp/native/Cargo.toml
- frostsnapp/native/src/api.rs
- frostsnapp/native/src/bridge_generated.io.rs
- frostsnapp/native/src/bridge_generated.web.rs
- frostsnapp/native/src/chain_sync.rs
- frostsnapp/native/src/coordinator.rs
- frostsnapp/native/src/wallet.rs
- justfile
* Upgrades bdk to version 0.12 with minor api changes.
* Patch keeps the keychain_txout_more_range changes from
https://github.com/bitcoindevkit/bdk/pull/1324,
* This bdk rev uses an updated electrum-client with upgraded rustls.
* Frostsnapp no longer depends on ring.
https://github.com/bitcoindevkit/rust-electrum-client/pull/132
Fixes: https://github.com/frostsnap/frostsnap/issues/116
> Update BDK to 0.15 with patches

- Cargo.lock
- Cargo.toml
- device/Cargo.toml
- device/src/bin/v2.rs
- device/src/esp32_run.rs
- device/src/io.rs
- device/src/st7789.rs
Compiles using the cst816s fork @musdom found.
Also upgrades to embedded_hal 1.0.
Currently the screen display is blank.
* The new `mipsi::Builder` wants to receive an `SpiDevice` and not the `SpiBus`, so we need to choose a CS pin? Not sure what to put here.
* Is `Orientation::Portrait(false)` equal to `Rotation:Deg90`?
* I'm also setting the reset pin to high (https://github.com/almindor/mipidsi/blob/master/docs/TROUBLESHOOTING.md)
> Upgrade esp-hal to 0.18.0

- frostsnapp/lib/device_action.dart
- frostsnapp/lib/device_settings.dart
- frostsnapp/lib/device_setup.dart
- frostsnapp/lib/hex.dart
- frostsnapp/lib/keygen.dart
- frostsnapp/lib/main.dart
- frostsnapp/lib/sign_message.dart
I changed the dialog that comes up for device actions to a https://api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html. To me this is much nicer because:
1. More space. Much less cramped on screen.
2. Natural way of closing it.
3. Let's you drag it down to see what's behind it and then resume.
This is on top of the PSBT PR #129
> Better device dialogs

- frostsnap_coordinator/src/backup.rs
- frostsnap_coordinator/src/firmware_upgrade.rs
- frostsnap_coordinator/src/keygen.rs
- frostsnap_coordinator/src/signing.rs
- frostsnap_coordinator/src/ui_protocol.rs
- frostsnap_core/src/coordinator.rs
- frostsnap_core/src/message.rs
- frostsnap_core/tests/common/mod.rs
- frostsnap_core/tests/endtoend.rs
- frostsnap_core/tests/malicious.rs
- frostsnapp/ios/Runner/bridge_generated.h
- frostsnapp/lib/bridge_definitions.dart
- frostsnapp/lib/bridge_generated.dart
- frostsnapp/lib/bridge_generated.io.dart
- frostsnapp/lib/bridge_generated.web.dart
- frostsnapp/lib/device_action.dart
- frostsnapp/lib/device_id_ext.dart
- frostsnapp/lib/device_list.dart
- frostsnapp/lib/keygen.dart
- frostsnapp/macos/Runner/bridge_generated.h
- frostsnapp/native/src/api.rs
- frostsnapp/native/src/bridge_generated.io.rs
- frostsnapp/native/src/bridge_generated.rs
- frostsnapp/native/src/bridge_generated.web.rs
- frostsnapp/native/src/coordinator.rs
Rather than the key generation just finishing when the devices ACK.
Also had to turn the test tooling message stack into a queue so they are
delivered in the actual order they were sent.
This means there's a new button to confirm the key generation in the dialog.
> Finalize keygen

- frostsnapp/lib/device_settings.dart
Oops I forgot to add this commit to #136
After a successful backup check the dialog doesn't close:
```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
type 'bool' is not a subtype of type 'Null' of 'result'
When the exception was thrown, this was the stack:
#0      LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:845:18)
#1      _RouteEntry.handlePop (package:flutter/src/widgets/navigator.dart:3167:16)
#2      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:4340:22)
#3      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5368:7)
#4      Navigator.pop (package:flutter/src/widgets/navigator.dart:2665:27)
#5 …
```
> Fix Closing Check Backup Dialog

- frostsnap_coordinator/src/signing.rs
- frostsnap_coordinator/src/verify_address.rs
- frostsnapp/android/app/build.gradle
- frostsnapp/android/app/src/debug/AndroidManifest.xml
- frostsnapp/android/app/src/main/AndroidManifest.xml
- frostsnapp/android/app/src/profile/AndroidManifest.xml
- frostsnapp/android/build.gradle
- frostsnapp/android/gradle.properties
- frostsnapp/android/gradle/wrapper/gradle-wrapper.properties
- frostsnapp/android/settings.gradle
- frostsnapp/lib/electrum_server_settings.dart
- frostsnapp/lib/hex.dart
- frostsnapp/native/src/coordinator.rs
- frostsnapp/pubspec.lock
- frostsnapp/pubspec.yaml
pending_for_outbox was no longer needed for anything but was being used to send messages to devices. These messages were always duplicates. This caused a panic when you had a device plugged in already before you went to sign.
> [native] Remove pending_for_outbox

- frostsnapp/lib/main.dart
- frostsnapp/native/src/api.rs
- frostsnapp/native/src/logger.rs
Previously, if the topmost flutter instance got popped, the app will end
up hanging at the startup screen. The culprit is
`tracing::subscriber::set_global_default` being called multiple times
(it should only be called once).
This commit changes the behavior so that future calls only replaces the
`StreamSink` (which is now a global variable).
> Fix: restart after topmost instance pop

- frostsnap_coordinator/src/verify_address.rs
- frostsnapp/lib/address.dart
- frostsnapp/native/src/api.rs
I broke it before and it is only used to pop an extra scope and I'm not even sure we want to do that.
> [coord+app] Remove verify_address/sent_to_devices

- device/src/bin/v2.rs
Tiny change so we keep track of binary sizes during development.
> [device] Show upgrade size

- frostsnap_comms/src/lib.rs
So that things happen faster during keygen. We should be able to handle this now that we use conch communication.
> [device] Increase baudrate to 115_200

- Cargo.toml
- frostsnap_coordinator/src/bitcoin/chain_sync.rs
They are not using ssl until we can control ssl certs more closely.
> [app] Use our electrum servers as default

- device/src/bin/v2.rs
- device/src/esp32_run.rs
- device/src/ota.rs
- device/src/ui.rs
distinguish between main workflows and busy tasks. Busy tasks shouldn't visuall interrupt main tasks.
> [device] Busy tasks shouldn't interrupt main tasks

- .github/actions/set-up-app-build/action.yml
- .github/workflows/test.yml
- frostsnapp/native/build.rs
- justfile
Turns out you can't easily `espflash flash` a binary, see https://github.com/viamrobotics/micro-rdk/pull/289
Need to use `espflash write-bin 0x10000 ~/tmp/firmware.bin` with specific flash addresses
> Upload firmware binary with actions

- frostsnap_coordinator/src/backup_run.rs
- frostsnap_coordinator/src/check_share.rs
- frostsnap_coordinator/src/display_backup.rs
- frostsnap_coordinator/src/lib.rs
- frostsnapp/lib/backup_workflow.dart
- frostsnapp/lib/contexts.dart
- frostsnapp/lib/device_settings.dart
- frostsnapp/lib/key_list.dart
- frostsnapp/lib/keygen.dart
- frostsnapp/lib/main.dart
- frostsnapp/lib/settings.dart
- frostsnapp/lib/show_backup.dart
- frostsnapp/lib/theme.dart
- frostsnapp/lib/wallet.dart
- frostsnapp/lib/wallet_send.dart
- frostsnapp/native/src/api.rs
Replaces #206
* Remove `BannerStateProvider`. Use a `ValueNotifier` in `WalletContext` instead.
* Use `ListTile` where able (instead of something custom).
* Move non-stream-dependent widgets out of the `StreamBuilder::builder`.
* Have the backup workflow within a modal sheet (instead of a page) for consistency.
> Backup workflow (2)

- frostsnapp/linux/rust.cmake
Fix build for more recent toolchains / rustup
See
https://github.com/GothenburgBitFactory/taskwarrior/issues/3810#issuecomment-2708925400
> [app] bump pinned corrosion version

- device/src/esp32_run.rs
- device/src/io.rs
- frostsnap_comms/src/lib.rs
- frostsnap_coordinator/src/serial_port.rs
- frostsnap_coordinator/src/usb_serial_manager.rs
Weird bugs in the Linux kernel driver for ACM CDC devices was being triggered by our aggressive disconnect and reconnect for devices that had finished firmware upgrade. It happened so fast that data got corrupted somehow by the CDC ACM control message `2122030000000000`. Now we only disconnect the port once the device has cleanly finished the upgrade and sent our reset signal.
> [comms] Devices send Reset signal when they reset

- frostsnap_coordinator/src/bitcoin/chain_sync.rs
- frostsnap_core/src/coordinator.rs
- frostsnap_core/src/device.rs
- frostsnap_core/src/message.rs
- frostsnapp/native/src/ffi_serial_port.rs
Worth noting that there were more warnings on https://github.com/frostsnap/frostsnap/pull/236 related to large enum variants.
> Make 1.87 clippy happy

- frostsnap_core/Cargo.toml
I don't understand how but people made breaking API changes in a minor version (1.7.0).
> [ci] Pin proptest for right rand dependency

- frostsnapp/pubspec.lock
- frostsnapp/pubspec.yaml
Fixes CI, see these jobs [1](https://github.com/frostsnap/frostsnap/actions/runs/16490316609/job/46624225511) [2](https://github.com/frostsnap/frostsnap/actions/runs/16490640843/job/46624282753)
No new functionality in 2.11 just bug fixes, [changelog](https://pub.dev/packages/flutter_rust_bridge/changelog).
> Update to flutter rust bridge 2.11.1

- device/src/esp32_run.rs
- device/src/ota.rs
- frostsnapp/lib/restoration.dart
- frostsnapp/pubspec.lock
Upgrading devices in a daisy chain from android mysteriously broke in 408870de7267d57097d874ada495d6f25169fd69.
The top-most device fails to read the ready signal from the downstream device after it has changed its BAUD rates, waiting forever it never reads in the firmware from the coordinator as it believes the downstream device is not ready.
Adding a small wait after changing BAUD rates ensures that every device is on the same page before communicating again.
edit: Lloyd acked me tacking on the app lint fixes here
> Wait after changing BAUD before OTA

- Cargo.lock
- Cargo.toml
- device/src/efuse.rs
- device/src/io.rs
- frostsnap_comms/Cargo.toml
- frostsnap_comms/src/lib.rs
- frostsnap_coordinator/src/persist.rs
- frostsnap_core/src/coordinator.rs
- frostsnap_core/src/coordinator/restoration.rs
- frostsnap_core/src/device.rs
- frostsnap_core/src/device/restoration.rs
- frostsnap_core/src/lib.rs
- frostsnap_core/src/macros.rs
- frostsnap_core/src/message.rs
- frostsnap_core/src/sign_task.rs
- frostsnap_core/src/symmetric_encryption.rs
- frostsnap_core/src/tweak.rs
- frostsnap_core/tests/common/mod.rs
- frostsnap_core/tests/endtoend.rs
- frostsnap_embedded/src/ab_write.rs
- frostsnap_embedded/src/nor_flash_log.rs
- frostsnapp/rust/src/api/coordinator.rs
- frostsnapp/rust/src/api/recovery.rs
- frostsnapp/rust/src/coordinator.rs
- Upgrade bincode from rc3 to 2.0.1
- Update to latest secp256kfun/schnorr_fun master
- Migrate from PartyIndex to ShareIndex
- Use upstream ShareImage instead of local definition
- Fix bincode::Decode bounds to use () context where functions control decoding
> Upgrade to bincode v2 and latest secp256kfun

- device/src/firmware_size.rs
This PR fixes an off-by-16 error in the firmware size calculation. The
issue was that we weren't accounting for the ESP32 checksum byte and its
padding.
- Account for the single-byte XOR checksum that ESP32 firmware includes
after segments
- Match the exact padding logic from the ESP-IDF bootloader
- The calculation now correctly adds:
1. Segments data
2. Checksum byte (+1)
3. Padding to 16-byte boundary
4. Optional SHA256 digest (if append_digest = 1)
> [ota] Fix firmware_size calc

- device/src/efuse.rs
- device/src/esp32_run.rs
- device/src/flash/header.rs
- frostsnap_core/src/device.rs
- frostsnap_core/src/device/restoration.rs
- frostsnap_core/src/device_nonces.rs
- frostsnap_core/tests/common/mod.rs
- frostsnap_core/tests/malicious.rs
This PR enables the devices to use their HMAC EFUSE keys for various secrets.
By using these EFUSE keys, an attacker wanting to extract the secrets would not only have to dump the flash from the device but they would additionally have to extract the relevant key from EFUSE; significantly more difficult (requiring chip decapping/probing or sophisticated sidechannel attacks). 
The device keypair is currently used for DeviceId and encryption of keygen shares sent to  other parties.
Since this keypair is created on startup, this call could prove weak to side-channel attacks. Because device keypair compromise only affects device identity and keygen share encryption (rather than signing keys themselves), we choose to use the less critical `fixed-entropy` HMAC for this purpose.
An attacker …
> Use HMAC for Device Secrets

- device/src/esp32_run.rs
- frostsnap_coordinator/src/lib.rs
- frostsnap_coordinator/src/nonce_replenish.rs
- frostsnap_core/src/coordinator.rs
- frostsnap_core/src/coordinator/coordinator_to_user.rs
- frostsnap_core/src/device.rs
- frostsnap_core/tests/common/mod.rs
- frostsnap_core/tests/endtoend.rs
- frostsnap_core/tests/proptest.rs
- frostsnapp/lib/device_action_name.dart
- frostsnapp/lib/nonce_replenish.dart
- frostsnapp/lib/restoration.dart
- frostsnapp/lib/stream_ext.dart
- frostsnapp/lib/wallet.dart
- frostsnapp/lib/wallet_create.dart
- frostsnapp/rust/src/api/mod.rs
- frostsnapp/rust/src/api/nonce_replenish.rs
- frostsnapp/rust/src/coordinator.rs
- frostsnapp/rust/src/sink_wrap.rs
There are two (similar) nonce-replenish UIs: one streamlined in the wallet creation workflow, and one generic that is called after wallet recovery. 
The determination on whether we need actually need to replenish nonces is somewhat unique since it is independent of having a key. For example you can reach the nonce-replenish screen and then back-out and revisit it. I have decided to always show it for consistency.
Should we also conditionally have this this generic widget display on the wallet home-screen if nonces get out of sync? Or alternatively, run it entirely in the background?
I stopped working on the device UI to display that it is generating nonces. The code for `BusyTask` was not being called due to new `WaitingFor` states, and after a minor rabbit hole trying to reimplement I …
> Nonce Generation UI Protocol

- frostsnap_core/src/device.rs
- frostsnap_core/src/device_nonces.rs
- frostsnap_core/tests/malicious.rs
We had a system to cache a signature we've just produced such that if we get asked to sign again we can just return it. But there were checks that returned errors before the cache was hit. We remove the errors. This means that attempts to reuse nonces are only caught after the user has confirmed.
> [core] Allow repeating the same sign requests

- Cargo.lock
- device/Cargo.toml
- device/src/factory/init.rs
- frostsnap_widgets/Cargo.toml
It's not used by anything except for factory initialization which doesn't seem to really need it either. It is also breaking some things in other branches when you enabled the fixed point arithmetic in embedded_graphics.
> [device] Remove embedded-text dependency

- cst816s/src/lib.rs
- device/src/panic.rs
- frostsnapp/android/app/src/main/kotlin/com/frostsnap/CdcAcmPlugin.kt
When restarting after a firmware update or after plugging in device to android coordinator, often the screen on the first device was blank.
When it is the first time the device has been plugged in the android jtag notice/accept caused a delay which resulted in screens operating fine
Restoring the delay for the touchscreen initalisation from 50ms to 400ms and also adding a 1000ms delay before opening the usb port from the android coordinator eliminated the blank screen issue.
> Fix blank screen issue on restart by adding delay to usb

- frostsnapp/android/settings.gradle
- frostsnapp/justfile
- frostsnapp/lib/settings.dart
- frostsnapp/pubspec.lock
- frostsnapp/pubspec.yaml
Displays:
- App version (default flutter version for now, will be changed in upcoming release PR), requires `package_info_plus` package. This package required kotlin 1.9.24 or greater.
- Bundled firmware digest, or `No firmware bundled`.
- Build commit (and whether it is "modified"), implemented via `just get-build-commit` and `flutter build --dart-define` flags.
> App Info in Settings

- cst816s/src/lib.rs
- device/src/ota.rs
- device/src/uart_interrupt.rs
- frostsnap_comms/src/lib.rs
There is some kind of hardware bug in esp32c3 that stops interrupts working properly during flash erases. Note that interrupts *are* disabled by default during flash erases in esp-storage but even if you turn that off,  1 in every 10 or so erases will be a "bad" erase that disables interrupts anyway. Note this has nothing to do with the content of the interrupt i.e. if it's in IRAM or not. I have no idea how this happens it seems very random.
So reducing the baudrate to this level means it takes around 67ms to transmit 128bytes to fill the FIFO which gives plenty of room.
To give an idea about how much this slows things down. It takes around 66ms to produce a nonce and around 34ms to transmit it at this baud rate so the majority of time is still spent doing multiplications rather than …
> [device] Reduce baudrate to 19_200 to stop overflows

- device/src/esp32_run.rs
- device/src/frosty_ui.rs
- device/src/ui.rs
- device/src/widget_tree.rs
- frostsnap_comms/src/fixed_string.rs
- frostsnap_comms/src/lib.rs
- frostsnap_coordinator/src/usb_serial_manager.rs
- frostsnap_widgets/src/standby.rs
- frostsnapp/lib/device_action_name.dart
- frostsnapp/lib/device_setup.dart
- frostsnapp/lib/global.dart
- frostsnapp/lib/restoration.dart
- frostsnapp/lib/wallet_create.dart
- frostsnapp/rust/src/api/coordinator.rs
- frostsnapp/rust/src/api/mod.rs
- frostsnapp/rust/src/api/name.rs
- frostsnapp/rust/src/coordinator.rs
This enforces string length limits for device names at the type level. It doesn't do key names because that's part of frostsnap_core but soft limits are in place.
Longer device names will stilld decode they'll just be truncated.
> [comms] Fixed length DeviceName and key name
