device/.cargo/config.toml, device/Cargo.toml, device/src/bin/frostypede.rs, device/src/lib.rs
bin and features to support the new custom PCB
=> Frostsnap Dev Board v1.1

.github/workflows/test.yml, coordinator-cli/src/device_namer.rs, coordinator-cli/src/main.rs, coordinator-cli/src/signer.rs, coordinator-cli/src/wallet.rs, device/src/esp32_run.rs, frostsnap_comms/src/lib.rs, frostsnap_coordinator/src/usb_serial_manager.rs, frostsnap_core/src/encrypted_share.rs, frostsnap_core/src/lib.rs, frostsnap_core/src/macros.rs, frostsnap_core/src/message.rs, frostsnap_core/tests/endtoend.rs
- Run clippy in ci
- Box the things
- Make DeviceId a `[u8;33]` to satisfy clippy in some areas
- Rename some things around `sign_task` because they bothered me
replaces #84
=> Run clippy in ci

device/src/bin/frostypede.rs, device/src/st7735.rs, justfile
One button interface requiring user to long press to confirm pending action required on device. This is meant to showcase a capacitive touch module but should also work with the current GPIO9 button until we get our next batch of devboards.
=> One button hold to confirm UI

frostsnap_core/tests/malicious.rs
Resolves https://github.com/frostsnap/frost-esp32/issues/14
Builds on and based on testing approach in https://github.com/frostsnap/frost-esp32/pull/66
=> Test for nonce reuse

device/Cargo.toml, device/src/bin/frostypede.rs, device/src/st7735.rs
Implements https://github.com/frostsnap/frostsnap/issues/98
=> Onscreen memory feature flag

frostsnap_core/src/coordinator.rs
* With the EncodedFrostKey PR we accidentally dropped the tweaks because we use a too-convenient into method.
* This meant we combined the signature shares without the tweak, causing invalid schnorr signatures in our bitcoin wallet.
* We now verify the signature after combining the signature shares.
=> Fix dropped tweak when combining signature shares

frostsnap_core/src/coordinator.rs, frostsnap_core/tests/endtoend.rs
Fixes https://github.com/frostsnap/frostsnap/issues/124
=> Allow over-replenishment of nonces

Cargo.lock, device/Cargo.toml, device/src/bin/v2.rs
They merged the new TRNG driver in esp-hal 0.19 so we can have true randomness again
=> Upgrade to esp-hal 0.19 and TRNG

Cargo.lock, device/src/bin/v2.rs, device/src/st7789.rs, frostsnap_core/src/device.rs, frostsnap_core/tests/endtoend.rs, frostsnapp/ios/Runner/bridge_generated.h, frostsnapp/lib/bridge_definitions.dart, frostsnapp/lib/bridge_definitions.freezed.dart, frostsnapp/lib/bridge_generated.dart, frostsnapp/lib/bridge_generated.io.dart, frostsnapp/lib/bridge_generated.web.dart, frostsnapp/lib/hex.dart, frostsnapp/lib/keygen.dart, frostsnapp/macos/Runner/bridge_generated.h, frostsnapp/native/Cargo.toml, frostsnapp/native/src/api.rs, frostsnapp/native/src/bridge_generated.io.rs, frostsnapp/native/src/bridge_generated.rs, frostsnapp/native/src/bridge_generated.web.rs
Uses schnorr_fun patch https://github.com/LLFourn/secp256kfun/pull/182
Also re-adds displaying backups after keygen, with backup instructions in-app.
=> Concise and formatted share backups

device/src/bin/v2.rs, device/src/st7789.rs, frostsnapp/lib/keygen.dart
TODO: Make the coordinator have a confirm button to actually finish the keygen.
[EDIT] I've decided against doing this TODO in this PR. https://github.com/frostsnap/frostsnap/issues/144
=> [device] Shortened keygen check

frostsnapp/lib/main.dart
Makes it easier to tell where the content is.
Also make dividers actually show.
=> Create appbar shadow

frostsnapp/lib/animated_check.dart, frostsnapp/lib/camera.dart, frostsnapp/lib/device.dart, frostsnapp/lib/device_action.dart, frostsnapp/lib/device_list.dart, frostsnapp/lib/device_settings.dart, frostsnapp/lib/key_list.dart, frostsnapp/lib/keygen.dart, frostsnapp/lib/main.dart, frostsnapp/lib/sign_message.dart, frostsnapp/lib/snowflake_animation.dart, frostsnapp/lib/theme.dart, frostsnapp/lib/wallet.dart
Basic global colours and theme. Feel free to experiment with different colours when testing!
=> App stylization

frostsnapp/lib/camera.dart, frostsnapp/lib/device_action.dart, frostsnapp/lib/device_list.dart, frostsnapp/lib/device_settings.dart, frostsnapp/lib/device_setup.dart, frostsnapp/lib/keygen.dart, frostsnapp/lib/sign_message.dart, frostsnapp/lib/theme.dart, frostsnapp/lib/wallet.dart
- Stop using a DraggableScrollableSheet since this is more complicated
than what we need and gets in the way of some gestures.
- Create DialogHeader which makes the formatting of the dialogs more consistent
- Device lists are always scrollable now and they show the scrollbar if they're long enough always.
=> Improve device action dialogs

device/src/bin/v2.rs, device/src/graphics/mod.rs, frostsnapp/lib/device_settings.dart, frostsnapp/lib/keygen.dart, frostsnapp/lib/theme.dart
Did this last night. Prompts the user to click the new device button in a more obvious way.
=> [device] Make nicer "new device" screen

frostsnapp/lib/device_settings.dart
It was lost in the electrum overhaul PR somehow
=> [app] Restore checking backup

device/src/esp32_run.rs, device/src/io.rs
quick fix for only using the high level trait everywhere.
I also added a debug message to debug how long it takes to persist stuff.
=> [device] clean up timer traits

Cargo.lock, Cargo.toml, frostsnap_coordinator/Cargo.toml, frostsnap_coordinator/src/bitcoin/chain_sync.rs, frostsnap_coordinator/src/bitcoin/wallet.rs, frostsnap_coordinator/src/bitcoin/wallet_persist.rs, frostsnapp/README.md, frostsnapp/native/src/api.rs
This allows us to persist floating txouts and has backwards compatibility built in.
=> Use BDK-maintained SQLite

.github/actions/upload-artifact/action.yml, .github/workflows/test.yml
=> Artifact upload action

device/src/bin/v2.rs, device/src/esp32_run.rs, device/src/graphics/mod.rs, device/src/ui.rs, frostsnap_core/src/device.rs, frostsnap_core/src/message.rs
Fixes https://github.com/frostsnap/frostsnap/issues/166
=> Show t-of-n on keygen confirmation screen

device/src/bin/v2.rs, device/src/graphics/mod.rs
Also remove some duplication between main and the panic handler
=> [device] Fix panic handler

frostsnap_coordinator/src/keygen.rs, frostsnap_core/src/coordinator.rs, frostsnap_core/src/device.rs, frostsnap_core/src/lib.rs, frostsnap_core/src/message.rs, frostsnap_core/tests/common/mod.rs, frostsnap_core/tests/endtoend.rs, frostsnap_core/tests/malicious.rs, frostsnapp/native/src/coordinator.rs
To simplify function parameters and return types.
Did this while working on nostr things. Looked worth salvaging.
=> [core] Add DoKeyGen and SendDoKeyGen

device/src/storage.rs
Based on #198.
Use nor flash properly. Never do erasure before writing. Just append
only in WORD_SIZE aligned chunks. Length prefix entries also.
=> [device] Use nor flash properly

Cargo.lock, Cargo.toml, frostsnap_core/src/coordinator.rs, frostsnap_core/tests/endtoend.rs, frostsnap_core/tests/malicious.rs, frostsnapp/native/src/coordinator.rs
=> Anti exfil

frostsnap_core/src/device.rs, frostsnap_core/src/device_nonces.rs, frostsnap_core/src/lib.rs, frostsnap_embedded/src/ab_write.rs, frostsnap_embedded/src/nonce_slots.rs
=> Erase nonce streams based on which one is least recently used

justfile
addresses regression from #216
=> [just] save image in just run

frostsnapp/lib/address.dart
=> Add missing wallet context on CheckAddressPage

frostsnapp/lib/device_settings.dart
Realized this doesn't matter once we move to having one key per device, but this was annoying me
=> Filter for relevant keys in device settings

frostsnapp/lib/backup_workflow.dart, frostsnapp/lib/keygen.dart
Ideas for improving the text of the workflow.
In other ideas, I think that we should use a stepper:
https://api.flutter.dev/flutter/material/Stepper-class.html
To do the:
1. Plug device in
2. Confirm to show backup on the device
3. Check the backup (skip-able)
4. unplug device so you can store it
5. done: reminder to keep it secure.
=> [app] Text bikesheading for backup workflow

device/src/bin/v2.rs, device/src/esp32_run.rs, device/src/graphics/widgets/bech32_input_preview.rs
These appeared because of a new stable version of rust
=> [device] Fix lints

Cargo.lock, frostsnap_coordinator/Cargo.toml, frostsnap_coordinator/src/bitcoin/chain_sync.rs, frostsnap_coordinator/src/settings.rs, frostsnapp/lib/electrum_server_settings.dart, frostsnapp/lib/wallet.dart, frostsnapp/lib/wallet_tx_details.dart, frostsnapp/rust/src/api/bitcoin.rs, frostsnapp/rust/src/api/settings.rs, frostsnapp/rust/src/api/signing.rs, frostsnapp/rust/src/api/super_wallet.rs
=> Backup Electrum Server and Ping-Pong logic

frostsnap_coordinator/src/backup_run.rs, frostsnap_coordinator/src/bitcoin/wallet_persist.rs, frostsnap_coordinator/src/frostsnap_persist.rs, frostsnap_coordinator/src/persist.rs, frostsnap_coordinator/src/settings.rs
* Add `Persist::migrate`.
* Rename `Persist::init` to `load` and `Persist::InitParams` to `LoadParams`.
=> Modify `Persist` to handle migrations

.github/actions/generate-frb/action.yml, .github/actions/install-cargo-bins/action.yml, .github/workflows/test.yml, fetch.just, frostsnap_coordinator/src/lib.rs, frostsnapp/justfile, frostsnapp/rust/src/api/init.rs, frostsnapp/rust/src/api/port.rs, justfile
time to dust off that windows partition
---
Tested and it works! Checked firmware upgrade, keygen, send, receive, restoration.
Serial port speeds are great (perhaps I was running debug build in the past, hence why i thought it was slow).
=> Build for Windows

frostsnapp/lib/device_action_backup.dart, frostsnapp/lib/device_action_backup_check.dart, frostsnapp/rust/src/api/coordinator.rs
No idea how managed to find this one @musdom, any tips to reproduce?
=> Don't assume share indexes from device list

Cargo.lock, Cargo.toml, cst816s/.cargo/config.toml, cst816s/.gitignore, cst816s/Cargo.toml, cst816s/LICENSE, cst816s/README.md, cst816s/src/lib.rs, device/Cargo.toml, device/src/bin/dev.rs, device/src/bin/frontier.rs, device/src/bin/widget_dev.rs, device/src/factory/init.rs, device/src/factory/screen_test.rs, device/src/frosty_ui.rs, device/src/lib.rs, device/src/peripherals.rs, device/src/resources.rs, device/src/touch_handler.rs, justfile
[cst] Use hardware IRQ so we don't miss touches 🫰
+ vendor the old crate here.
+ Make the Peripherals into a static ref
+ unify touch calibration
=> CST IRQ LFG Edition 🫰🫰🫰

frostsnap_widgets/src/backup/backup_display.rs, frostsnap_widgets/src/firmware_upgrade.rs, frostsnap_widgets/src/page_slider.rs, frostsnap_widgets/src/palette.rs, frostsnap_widgets/src/sign_prompt.rs
Things I improved while testing
=> [dev-ui] Misc tweaks

device/src/esp32_run.rs, device/src/flash/log.rs, frostsnap_coordinator/src/frostsnap_persist.rs, frostsnap_coordinator/src/keygen.rs, frostsnap_coordinator/src/verify_address.rs, frostsnap_core/src/coordinator.rs, frostsnap_core/src/coordinator/keys.rs, frostsnap_core/src/coordinator/restoration.rs, frostsnap_core/src/coordinator/signing.rs, frostsnap_core/src/device.rs, frostsnap_core/src/device/keys.rs, frostsnap_core/src/device/restoration.rs, frostsnap_core/src/message.rs, frostsnap_core/src/message/keygen.rs, frostsnap_core/src/message/screen_verify.rs, frostsnap_core/src/message/signing.rs, frostsnap_core/tests/common/mod.rs, frostsnap_core/tests/malicious.rs, frostsnap_core/tests/proptest.rs, frostsnapp/rust/src/coordinator.rs
Because it's a breaking change to do this later.
It also includes an API improvement with `BeginKeygen` (the first commit).
=> Modularize enums

Cargo.lock, frostsnap_coordinator/Cargo.toml, frostsnap_coordinator/src/cdc_acm_usb.rs, frostsnap_coordinator/src/serial_port.rs, frostsnapp/rust/src/api/init.rs
The new nusb version apparently fixes the issue with devices getting
stuck writing to JTAG. It handles the usb tx logic internally and just
gives (mostly) nice high level APIs.
=> Upgrade nusb

device/src/ota.rs
This doesn't lead to problems on master but does elsewhere!
=> [device] Fix weird type inference thing in ota.rs

cst816s/src/lib.rs
Problem: Touch screens become unresponsive when touched during device boot. Testing revealed that holding touch during startup causes a race condition where the interrupt fires before the handler is registered.
Changes:
- Move touch controller setup into register() function for atomic initialization
- Register interrupt handler BEFORE enabling interrupt pin (critical fix)
- Remove interrupt enable from new_esp32() constructor
- Optimize reset recovery delay from 400ms to 50ms
- Add delay parameter to register() function
The key fix is ensuring the interrupt handler is registered before the interrupt pin is enabled. This prevents interrupts from firing without a handler, which was causing the touch system to enter an undefined state.
Testing confirmed that just changing the handler …
=> Fix touch screen freeze when pressed during startup
